#Try to find the digital_rf c library and headers using pkg-config

find_package(PkgConfig)
pkg_check_modules(DIGITALRF REQUIRED digital_rf)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DIGITALRF  DEFAULT_MSG  DIGITALRF_LIBRARIES DIGITALRF_INCLUDE_DIRS DIGITALRF_CFLAGS DIGITALRF_LDFLAGS)

if(DIGITALRF_FOUND)
    set(DIGITALRF_LIBRARIES ${DIGITALRF_LIBRARIES} )
    set(DIGITALRF_INCLUDE_DIRS ${DIGITALRF_INCLUDE_DIRS} )
    set(DIGITALRF_CFLAGS ${DIGITALRF_CFLAGS} )
    set(DIGITALRF_LDFLAGS ${DIGITALRF_LDFLAGS} )
endif(DIGITALRF_FOUND)

mark_as_advanced(DIGITALRF_INCLUDE_DIRS DIGITALRF_LIBRARIES DIGITALRF_CFLAGS DIGITALRF_LDLAGS )
